server:
  name: "sso-svc"
  port: ":8000"
  log:
    level: "debug"
    format: "text"

database:
  sql:
    url: "postgresql://postgres:postgres@localhost:7777/postgres?sslmode=disable"

oauth:
  google:
    client_id: "client_id"
    client_secret: "megasupersecret"
    redirect_url: "http://localhost:8000/v1/sso/google/login/callback"

jwt:
  user:
    access_token:
      secret_key: "UnG06MAU2i1Mvqf8" #example
      token_lifetime: 900
    refresh_token:
      secret_key: "6DSjhhT9KIezubpR" #example
      encryption_key: "Zlyh20N8uojZHFdO"  # Key for decrypting Refresh Token in the database
      token_lifetime: 604800
  service:
    secret_key: "H6eHCV0rKzJIAEVE" #example

kafka:
  brokers:
    - "re-news-kafka:29092"

swagger:
  enabled: true
  url: "/swagger"
  port: "8080"