/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ReNewsChainsAuthV1OwnGet400Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ReNewsChainsAuthV1OwnGet400Response{}

// ReNewsChainsAuthV1OwnGet400Response Standard JSON:API error
type ReNewsChainsAuthV1OwnGet400Response struct {
	// Non empty array of errors occurred during request processing
	Errors []ReNewsChainsAuthV1OwnGet400ResponseErrorsInner `json:"errors"`
}

type _ReNewsChainsAuthV1OwnGet400Response ReNewsChainsAuthV1OwnGet400Response

// NewReNewsChainsAuthV1OwnGet400Response instantiates a new ReNewsChainsAuthV1OwnGet400Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReNewsChainsAuthV1OwnGet400Response(errors []ReNewsChainsAuthV1OwnGet400ResponseErrorsInner) *ReNewsChainsAuthV1OwnGet400Response {
	this := ReNewsChainsAuthV1OwnGet400Response{}
	this.Errors = errors
	return &this
}

// NewReNewsChainsAuthV1OwnGet400ResponseWithDefaults instantiates a new ReNewsChainsAuthV1OwnGet400Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReNewsChainsAuthV1OwnGet400ResponseWithDefaults() *ReNewsChainsAuthV1OwnGet400Response {
	this := ReNewsChainsAuthV1OwnGet400Response{}
	return &this
}

// GetErrors returns the Errors field value
func (o *ReNewsChainsAuthV1OwnGet400Response) GetErrors() []ReNewsChainsAuthV1OwnGet400ResponseErrorsInner {
	if o == nil {
		var ret []ReNewsChainsAuthV1OwnGet400ResponseErrorsInner
		return ret
	}

	return o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value
// and a boolean to check if the value has been set.
func (o *ReNewsChainsAuthV1OwnGet400Response) GetErrorsOk() ([]ReNewsChainsAuthV1OwnGet400ResponseErrorsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Errors, true
}

// SetErrors sets field value
func (o *ReNewsChainsAuthV1OwnGet400Response) SetErrors(v []ReNewsChainsAuthV1OwnGet400ResponseErrorsInner) {
	o.Errors = v
}

func (o ReNewsChainsAuthV1OwnGet400Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ReNewsChainsAuthV1OwnGet400Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["errors"] = o.Errors
	return toSerialize, nil
}

func (o *ReNewsChainsAuthV1OwnGet400Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"errors",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varReNewsChainsAuthV1OwnGet400Response := _ReNewsChainsAuthV1OwnGet400Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varReNewsChainsAuthV1OwnGet400Response)

	if err != nil {
		return err
	}

	*o = ReNewsChainsAuthV1OwnGet400Response(varReNewsChainsAuthV1OwnGet400Response)

	return err
}

type NullableReNewsChainsAuthV1OwnGet400Response struct {
	value *ReNewsChainsAuthV1OwnGet400Response
	isSet bool
}

func (v NullableReNewsChainsAuthV1OwnGet400Response) Get() *ReNewsChainsAuthV1OwnGet400Response {
	return v.value
}

func (v *NullableReNewsChainsAuthV1OwnGet400Response) Set(val *ReNewsChainsAuthV1OwnGet400Response) {
	v.value = val
	v.isSet = true
}

func (v NullableReNewsChainsAuthV1OwnGet400Response) IsSet() bool {
	return v.isSet
}

func (v *NullableReNewsChainsAuthV1OwnGet400Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReNewsChainsAuthV1OwnGet400Response(val *ReNewsChainsAuthV1OwnGet400Response) *NullableReNewsChainsAuthV1OwnGet400Response {
	return &NullableReNewsChainsAuthV1OwnGet400Response{value: val, isSet: true}
}

func (v NullableReNewsChainsAuthV1OwnGet400Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReNewsChainsAuthV1OwnGet400Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


