/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SessionsCollectionData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SessionsCollectionData{}

// SessionsCollectionData struct for SessionsCollectionData
type SessionsCollectionData struct {
	Type string `json:"type"`
	Attributes SessionsCollectionDataAttributes `json:"attributes"`
}

type _SessionsCollectionData SessionsCollectionData

// NewSessionsCollectionData instantiates a new SessionsCollectionData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSessionsCollectionData(type_ string, attributes SessionsCollectionDataAttributes) *SessionsCollectionData {
	this := SessionsCollectionData{}
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewSessionsCollectionDataWithDefaults instantiates a new SessionsCollectionData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSessionsCollectionDataWithDefaults() *SessionsCollectionData {
	this := SessionsCollectionData{}
	return &this
}

// GetType returns the Type field value
func (o *SessionsCollectionData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *SessionsCollectionData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *SessionsCollectionData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *SessionsCollectionData) GetAttributes() SessionsCollectionDataAttributes {
	if o == nil {
		var ret SessionsCollectionDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *SessionsCollectionData) GetAttributesOk() (*SessionsCollectionDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *SessionsCollectionData) SetAttributes(v SessionsCollectionDataAttributes) {
	o.Attributes = v
}

func (o SessionsCollectionData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SessionsCollectionData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *SessionsCollectionData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSessionsCollectionData := _SessionsCollectionData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSessionsCollectionData)

	if err != nil {
		return err
	}

	*o = SessionsCollectionData(varSessionsCollectionData)

	return err
}

type NullableSessionsCollectionData struct {
	value *SessionsCollectionData
	isSet bool
}

func (v NullableSessionsCollectionData) Get() *SessionsCollectionData {
	return v.value
}

func (v *NullableSessionsCollectionData) Set(val *SessionsCollectionData) {
	v.value = val
	v.isSet = true
}

func (v NullableSessionsCollectionData) IsSet() bool {
	return v.isSet
}

func (v *NullableSessionsCollectionData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSessionsCollectionData(val *SessionsCollectionData) *NullableSessionsCollectionData {
	return &NullableSessionsCollectionData{value: val, isSet: true}
}

func (v NullableSessionsCollectionData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSessionsCollectionData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


