/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RegisterUserDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RegisterUserDataAttributes{}

// RegisterUserDataAttributes struct for RegisterUserDataAttributes
type RegisterUserDataAttributes struct {
	// The user's email address.
	Email string `json:"email"`
	// The user's password.
	Password string `json:"password"`
	// Confirmation of the user's password. Must match the password field.
	ConfirmPassword string `json:"confirm_password"`
}

type _RegisterUserDataAttributes RegisterUserDataAttributes

// NewRegisterUserDataAttributes instantiates a new RegisterUserDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRegisterUserDataAttributes(email string, password string, confirmPassword string) *RegisterUserDataAttributes {
	this := RegisterUserDataAttributes{}
	this.Email = email
	this.Password = password
	this.ConfirmPassword = confirmPassword
	return &this
}

// NewRegisterUserDataAttributesWithDefaults instantiates a new RegisterUserDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRegisterUserDataAttributesWithDefaults() *RegisterUserDataAttributes {
	this := RegisterUserDataAttributes{}
	return &this
}

// GetEmail returns the Email field value
func (o *RegisterUserDataAttributes) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *RegisterUserDataAttributes) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *RegisterUserDataAttributes) SetEmail(v string) {
	o.Email = v
}

// GetPassword returns the Password field value
func (o *RegisterUserDataAttributes) GetPassword() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Password
}

// GetPasswordOk returns a tuple with the Password field value
// and a boolean to check if the value has been set.
func (o *RegisterUserDataAttributes) GetPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Password, true
}

// SetPassword sets field value
func (o *RegisterUserDataAttributes) SetPassword(v string) {
	o.Password = v
}

// GetConfirmPassword returns the ConfirmPassword field value
func (o *RegisterUserDataAttributes) GetConfirmPassword() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ConfirmPassword
}

// GetConfirmPasswordOk returns a tuple with the ConfirmPassword field value
// and a boolean to check if the value has been set.
func (o *RegisterUserDataAttributes) GetConfirmPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ConfirmPassword, true
}

// SetConfirmPassword sets field value
func (o *RegisterUserDataAttributes) SetConfirmPassword(v string) {
	o.ConfirmPassword = v
}

func (o RegisterUserDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RegisterUserDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["email"] = o.Email
	toSerialize["password"] = o.Password
	toSerialize["confirm_password"] = o.ConfirmPassword
	return toSerialize, nil
}

func (o *RegisterUserDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"email",
		"password",
		"confirm_password",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRegisterUserDataAttributes := _RegisterUserDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRegisterUserDataAttributes)

	if err != nil {
		return err
	}

	*o = RegisterUserDataAttributes(varRegisterUserDataAttributes)

	return err
}

type NullableRegisterUserDataAttributes struct {
	value *RegisterUserDataAttributes
	isSet bool
}

func (v NullableRegisterUserDataAttributes) Get() *RegisterUserDataAttributes {
	return v.value
}

func (v *NullableRegisterUserDataAttributes) Set(val *RegisterUserDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableRegisterUserDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableRegisterUserDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRegisterUserDataAttributes(val *RegisterUserDataAttributes) *NullableRegisterUserDataAttributes {
	return &NullableRegisterUserDataAttributes{value: val, isSet: true}
}

func (v NullableRegisterUserDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRegisterUserDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


