/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RegisterUserData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RegisterUserData{}

// RegisterUserData struct for RegisterUserData
type RegisterUserData struct {
	Type string `json:"type"`
	Attributes RegisterUserDataAttributes `json:"attributes"`
}

type _RegisterUserData RegisterUserData

// NewRegisterUserData instantiates a new RegisterUserData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRegisterUserData(type_ string, attributes RegisterUserDataAttributes) *RegisterUserData {
	this := RegisterUserData{}
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewRegisterUserDataWithDefaults instantiates a new RegisterUserData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRegisterUserDataWithDefaults() *RegisterUserData {
	this := RegisterUserData{}
	return &this
}

// GetType returns the Type field value
func (o *RegisterUserData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *RegisterUserData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *RegisterUserData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *RegisterUserData) GetAttributes() RegisterUserDataAttributes {
	if o == nil {
		var ret RegisterUserDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *RegisterUserData) GetAttributesOk() (*RegisterUserDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *RegisterUserData) SetAttributes(v RegisterUserDataAttributes) {
	o.Attributes = v
}

func (o RegisterUserData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RegisterUserData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *RegisterUserData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRegisterUserData := _RegisterUserData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRegisterUserData)

	if err != nil {
		return err
	}

	*o = RegisterUserData(varRegisterUserData)

	return err
}

type NullableRegisterUserData struct {
	value *RegisterUserData
	isSet bool
}

func (v NullableRegisterUserData) Get() *RegisterUserData {
	return v.value
}

func (v *NullableRegisterUserData) Set(val *RegisterUserData) {
	v.value = val
	v.isSet = true
}

func (v NullableRegisterUserData) IsSet() bool {
	return v.isSet
}

func (v *NullableRegisterUserData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRegisterUserData(val *RegisterUserData) *NullableRegisterUserData {
	return &NullableRegisterUserData{value: val, isSet: true}
}

func (v NullableRegisterUserData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRegisterUserData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


