/*
Cifra SSO REST API

SSO REST API for Cifra services

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the LoginDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LoginDataAttributes{}

// LoginDataAttributes struct for LoginDataAttributes
type LoginDataAttributes struct {
	// The user's email address.
	Email string `json:"email"`
	// The user's password.
	Password string `json:"password"`
}

type _LoginDataAttributes LoginDataAttributes

// NewLoginDataAttributes instantiates a new LoginDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLoginDataAttributes(email string, password string) *LoginDataAttributes {
	this := LoginDataAttributes{}
	this.Email = email
	this.Password = password
	return &this
}

// NewLoginDataAttributesWithDefaults instantiates a new LoginDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLoginDataAttributesWithDefaults() *LoginDataAttributes {
	this := LoginDataAttributes{}
	return &this
}

// GetEmail returns the Email field value
func (o *LoginDataAttributes) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *LoginDataAttributes) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *LoginDataAttributes) SetEmail(v string) {
	o.Email = v
}

// GetPassword returns the Password field value
func (o *LoginDataAttributes) GetPassword() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Password
}

// GetPasswordOk returns a tuple with the Password field value
// and a boolean to check if the value has been set.
func (o *LoginDataAttributes) GetPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Password, true
}

// SetPassword sets field value
func (o *LoginDataAttributes) SetPassword(v string) {
	o.Password = v
}

func (o LoginDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LoginDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["email"] = o.Email
	toSerialize["password"] = o.Password
	return toSerialize, nil
}

func (o *LoginDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"email",
		"password",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLoginDataAttributes := _LoginDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLoginDataAttributes)

	if err != nil {
		return err
	}

	*o = LoginDataAttributes(varLoginDataAttributes)

	return err
}

type NullableLoginDataAttributes struct {
	value *LoginDataAttributes
	isSet bool
}

func (v NullableLoginDataAttributes) Get() *LoginDataAttributes {
	return v.value
}

func (v *NullableLoginDataAttributes) Set(val *LoginDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableLoginDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableLoginDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLoginDataAttributes(val *LoginDataAttributes) *NullableLoginDataAttributes {
	return &NullableLoginDataAttributes{value: val, isSet: true}
}

func (v NullableLoginDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLoginDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


