/*
Cifra SSO REST API

SSO REST API for Cifra services

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RegisterUser type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RegisterUser{}

// RegisterUser struct for RegisterUser
type RegisterUser struct {
	Data RegisterUserData `json:"data"`
}

type _RegisterUser RegisterUser

// NewRegisterUser instantiates a new RegisterUser object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRegisterUser(data RegisterUserData) *RegisterUser {
	this := RegisterUser{}
	this.Data = data
	return &this
}

// NewRegisterUserWithDefaults instantiates a new RegisterUser object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRegisterUserWithDefaults() *RegisterUser {
	this := RegisterUser{}
	return &this
}

// GetData returns the Data field value
func (o *RegisterUser) GetData() RegisterUserData {
	if o == nil {
		var ret RegisterUserData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *RegisterUser) GetDataOk() (*RegisterUserData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *RegisterUser) SetData(v RegisterUserData) {
	o.Data = v
}

func (o RegisterUser) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RegisterUser) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *RegisterUser) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRegisterUser := _RegisterUser{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRegisterUser)

	if err != nil {
		return err
	}

	*o = RegisterUser(varRegisterUser)

	return err
}

type NullableRegisterUser struct {
	value *RegisterUser
	isSet bool
}

func (v NullableRegisterUser) Get() *RegisterUser {
	return v.value
}

func (v *NullableRegisterUser) Set(val *RegisterUser) {
	v.value = val
	v.isSet = true
}

func (v NullableRegisterUser) IsSet() bool {
	return v.isSet
}

func (v *NullableRegisterUser) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRegisterUser(val *RegisterUser) *NullableRegisterUser {
	return &NullableRegisterUser{value: val, isSet: true}
}

func (v NullableRegisterUser) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRegisterUser) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


