/*
Cifra SSO REST API

SSO REST API for Cifra services

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RegisterAdmin type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RegisterAdmin{}

// RegisterAdmin struct for RegisterAdmin
type RegisterAdmin struct {
	Data RegisterAdminData `json:"data"`
}

type _RegisterAdmin RegisterAdmin

// NewRegisterAdmin instantiates a new RegisterAdmin object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRegisterAdmin(data RegisterAdminData) *RegisterAdmin {
	this := RegisterAdmin{}
	this.Data = data
	return &this
}

// NewRegisterAdminWithDefaults instantiates a new RegisterAdmin object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRegisterAdminWithDefaults() *RegisterAdmin {
	this := RegisterAdmin{}
	return &this
}

// GetData returns the Data field value
func (o *RegisterAdmin) GetData() RegisterAdminData {
	if o == nil {
		var ret RegisterAdminData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *RegisterAdmin) GetDataOk() (*RegisterAdminData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *RegisterAdmin) SetData(v RegisterAdminData) {
	o.Data = v
}

func (o RegisterAdmin) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RegisterAdmin) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *RegisterAdmin) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRegisterAdmin := _RegisterAdmin{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRegisterAdmin)

	if err != nil {
		return err
	}

	*o = RegisterAdmin(varRegisterAdmin)

	return err
}

type NullableRegisterAdmin struct {
	value *RegisterAdmin
	isSet bool
}

func (v NullableRegisterAdmin) Get() *RegisterAdmin {
	return v.value
}

func (v *NullableRegisterAdmin) Set(val *RegisterAdmin) {
	v.value = val
	v.isSet = true
}

func (v NullableRegisterAdmin) IsSet() bool {
	return v.isSet
}

func (v *NullableRegisterAdmin) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRegisterAdmin(val *RegisterAdmin) *NullableRegisterAdmin {
	return &NullableRegisterAdmin{value: val, isSet: true}
}

func (v NullableRegisterAdmin) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRegisterAdmin) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


