/*
Cifra SSO REST API

SSO REST API for Cifra services

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RegisterAdminDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RegisterAdminDataAttributes{}

// RegisterAdminDataAttributes struct for RegisterAdminDataAttributes
type RegisterAdminDataAttributes struct {
	// The user's email address.
	Email string `json:"email"`
	// The user's password.
	Password string `json:"password"`
	// The role assigned to the registering user.
	Role string `json:"role"`
}

type _RegisterAdminDataAttributes RegisterAdminDataAttributes

// NewRegisterAdminDataAttributes instantiates a new RegisterAdminDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRegisterAdminDataAttributes(email string, password string, role string) *RegisterAdminDataAttributes {
	this := RegisterAdminDataAttributes{}
	this.Email = email
	this.Password = password
	this.Role = role
	return &this
}

// NewRegisterAdminDataAttributesWithDefaults instantiates a new RegisterAdminDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRegisterAdminDataAttributesWithDefaults() *RegisterAdminDataAttributes {
	this := RegisterAdminDataAttributes{}
	return &this
}

// GetEmail returns the Email field value
func (o *RegisterAdminDataAttributes) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *RegisterAdminDataAttributes) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *RegisterAdminDataAttributes) SetEmail(v string) {
	o.Email = v
}

// GetPassword returns the Password field value
func (o *RegisterAdminDataAttributes) GetPassword() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Password
}

// GetPasswordOk returns a tuple with the Password field value
// and a boolean to check if the value has been set.
func (o *RegisterAdminDataAttributes) GetPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Password, true
}

// SetPassword sets field value
func (o *RegisterAdminDataAttributes) SetPassword(v string) {
	o.Password = v
}

// GetRole returns the Role field value
func (o *RegisterAdminDataAttributes) GetRole() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Role
}

// GetRoleOk returns a tuple with the Role field value
// and a boolean to check if the value has been set.
func (o *RegisterAdminDataAttributes) GetRoleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Role, true
}

// SetRole sets field value
func (o *RegisterAdminDataAttributes) SetRole(v string) {
	o.Role = v
}

func (o RegisterAdminDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RegisterAdminDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["email"] = o.Email
	toSerialize["password"] = o.Password
	toSerialize["role"] = o.Role
	return toSerialize, nil
}

func (o *RegisterAdminDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"email",
		"password",
		"role",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRegisterAdminDataAttributes := _RegisterAdminDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRegisterAdminDataAttributes)

	if err != nil {
		return err
	}

	*o = RegisterAdminDataAttributes(varRegisterAdminDataAttributes)

	return err
}

type NullableRegisterAdminDataAttributes struct {
	value *RegisterAdminDataAttributes
	isSet bool
}

func (v NullableRegisterAdminDataAttributes) Get() *RegisterAdminDataAttributes {
	return v.value
}

func (v *NullableRegisterAdminDataAttributes) Set(val *RegisterAdminDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableRegisterAdminDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableRegisterAdminDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRegisterAdminDataAttributes(val *RegisterAdminDataAttributes) *NullableRegisterAdminDataAttributes {
	return &NullableRegisterAdminDataAttributes{value: val, isSet: true}
}

func (v NullableRegisterAdminDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRegisterAdminDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


