/*
Cifra SSO REST API

SSO REST API for Cifra services

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"github.com/google/uuid"
	"time"
	"bytes"
	"fmt"
)

// checks if the UserDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserDataAttributes{}

// UserDataAttributes struct for UserDataAttributes
type UserDataAttributes struct {
	// Email
	Email string `json:"email"`
	// Role
	Role string `json:"role"`
	// Email Verified
	EmailVerified bool `json:"email_verified"`
	// Created At
	CreatedAt time.Time `json:"created_at"`
	// City ID
	CityId *uuid.UUID `json:"city_id,omitempty"`
	// Admin
	CityRole *string `json:"city_role,omitempty"`
	// Company ID
	CompanyId *uuid.UUID `json:"company_id,omitempty"`
	// Moder
	CompanyRole *string `json:"company_role,omitempty"`
	// Updated At
	UpdatedAt time.Time `json:"updated_at"`
}

type _UserDataAttributes UserDataAttributes

// NewUserDataAttributes instantiates a new UserDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserDataAttributes(email string, role string, emailVerified bool, createdAt time.Time, updatedAt time.Time) *UserDataAttributes {
	this := UserDataAttributes{}
	this.Email = email
	this.Role = role
	this.EmailVerified = emailVerified
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	return &this
}

// NewUserDataAttributesWithDefaults instantiates a new UserDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserDataAttributesWithDefaults() *UserDataAttributes {
	this := UserDataAttributes{}
	return &this
}

// GetEmail returns the Email field value
func (o *UserDataAttributes) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *UserDataAttributes) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *UserDataAttributes) SetEmail(v string) {
	o.Email = v
}

// GetRole returns the Role field value
func (o *UserDataAttributes) GetRole() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Role
}

// GetRoleOk returns a tuple with the Role field value
// and a boolean to check if the value has been set.
func (o *UserDataAttributes) GetRoleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Role, true
}

// SetRole sets field value
func (o *UserDataAttributes) SetRole(v string) {
	o.Role = v
}

// GetEmailVerified returns the EmailVerified field value
func (o *UserDataAttributes) GetEmailVerified() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.EmailVerified
}

// GetEmailVerifiedOk returns a tuple with the EmailVerified field value
// and a boolean to check if the value has been set.
func (o *UserDataAttributes) GetEmailVerifiedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EmailVerified, true
}

// SetEmailVerified sets field value
func (o *UserDataAttributes) SetEmailVerified(v bool) {
	o.EmailVerified = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *UserDataAttributes) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *UserDataAttributes) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *UserDataAttributes) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetCityId returns the CityId field value if set, zero value otherwise.
func (o *UserDataAttributes) GetCityId() uuid.UUID {
	if o == nil || IsNil(o.CityId) {
		var ret uuid.UUID
		return ret
	}
	return *o.CityId
}

// GetCityIdOk returns a tuple with the CityId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserDataAttributes) GetCityIdOk() (*uuid.UUID, bool) {
	if o == nil || IsNil(o.CityId) {
		return nil, false
	}
	return o.CityId, true
}

// HasCityId returns a boolean if a field has been set.
func (o *UserDataAttributes) HasCityId() bool {
	if o != nil && !IsNil(o.CityId) {
		return true
	}

	return false
}

// SetCityId gets a reference to the given uuid.UUID and assigns it to the CityId field.
func (o *UserDataAttributes) SetCityId(v uuid.UUID) {
	o.CityId = &v
}

// GetCityRole returns the CityRole field value if set, zero value otherwise.
func (o *UserDataAttributes) GetCityRole() string {
	if o == nil || IsNil(o.CityRole) {
		var ret string
		return ret
	}
	return *o.CityRole
}

// GetCityRoleOk returns a tuple with the CityRole field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserDataAttributes) GetCityRoleOk() (*string, bool) {
	if o == nil || IsNil(o.CityRole) {
		return nil, false
	}
	return o.CityRole, true
}

// HasCityRole returns a boolean if a field has been set.
func (o *UserDataAttributes) HasCityRole() bool {
	if o != nil && !IsNil(o.CityRole) {
		return true
	}

	return false
}

// SetCityRole gets a reference to the given string and assigns it to the CityRole field.
func (o *UserDataAttributes) SetCityRole(v string) {
	o.CityRole = &v
}

// GetCompanyId returns the CompanyId field value if set, zero value otherwise.
func (o *UserDataAttributes) GetCompanyId() uuid.UUID {
	if o == nil || IsNil(o.CompanyId) {
		var ret uuid.UUID
		return ret
	}
	return *o.CompanyId
}

// GetCompanyIdOk returns a tuple with the CompanyId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserDataAttributes) GetCompanyIdOk() (*uuid.UUID, bool) {
	if o == nil || IsNil(o.CompanyId) {
		return nil, false
	}
	return o.CompanyId, true
}

// HasCompanyId returns a boolean if a field has been set.
func (o *UserDataAttributes) HasCompanyId() bool {
	if o != nil && !IsNil(o.CompanyId) {
		return true
	}

	return false
}

// SetCompanyId gets a reference to the given uuid.UUID and assigns it to the CompanyId field.
func (o *UserDataAttributes) SetCompanyId(v uuid.UUID) {
	o.CompanyId = &v
}

// GetCompanyRole returns the CompanyRole field value if set, zero value otherwise.
func (o *UserDataAttributes) GetCompanyRole() string {
	if o == nil || IsNil(o.CompanyRole) {
		var ret string
		return ret
	}
	return *o.CompanyRole
}

// GetCompanyRoleOk returns a tuple with the CompanyRole field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserDataAttributes) GetCompanyRoleOk() (*string, bool) {
	if o == nil || IsNil(o.CompanyRole) {
		return nil, false
	}
	return o.CompanyRole, true
}

// HasCompanyRole returns a boolean if a field has been set.
func (o *UserDataAttributes) HasCompanyRole() bool {
	if o != nil && !IsNil(o.CompanyRole) {
		return true
	}

	return false
}

// SetCompanyRole gets a reference to the given string and assigns it to the CompanyRole field.
func (o *UserDataAttributes) SetCompanyRole(v string) {
	o.CompanyRole = &v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *UserDataAttributes) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *UserDataAttributes) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *UserDataAttributes) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

func (o UserDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["email"] = o.Email
	toSerialize["role"] = o.Role
	toSerialize["email_verified"] = o.EmailVerified
	toSerialize["created_at"] = o.CreatedAt
	if !IsNil(o.CityId) {
		toSerialize["city_id"] = o.CityId
	}
	if !IsNil(o.CityRole) {
		toSerialize["city_role"] = o.CityRole
	}
	if !IsNil(o.CompanyId) {
		toSerialize["company_id"] = o.CompanyId
	}
	if !IsNil(o.CompanyRole) {
		toSerialize["company_role"] = o.CompanyRole
	}
	toSerialize["updated_at"] = o.UpdatedAt
	return toSerialize, nil
}

func (o *UserDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"email",
		"role",
		"email_verified",
		"created_at",
		"updated_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUserDataAttributes := _UserDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUserDataAttributes)

	if err != nil {
		return err
	}

	*o = UserDataAttributes(varUserDataAttributes)

	return err
}

type NullableUserDataAttributes struct {
	value *UserDataAttributes
	isSet bool
}

func (v NullableUserDataAttributes) Get() *UserDataAttributes {
	return v.value
}

func (v *NullableUserDataAttributes) Set(val *UserDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableUserDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableUserDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserDataAttributes(val *UserDataAttributes) *NullableUserDataAttributes {
	return &NullableUserDataAttributes{value: val, isSet: true}
}

func (v NullableUserDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


