/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UserSessionCollection type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserSessionCollection{}

// UserSessionCollection struct for UserSessionCollection
type UserSessionCollection struct {
	Data UserSessionsData `json:"data"`
}

type _UserSessionCollection UserSessionCollection

// NewUserSessionCollection instantiates a new UserSessionCollection object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserSessionCollection(data UserSessionsData) *UserSessionCollection {
	this := UserSessionCollection{}
	this.Data = data
	return &this
}

// NewUserSessionCollectionWithDefaults instantiates a new UserSessionCollection object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserSessionCollectionWithDefaults() *UserSessionCollection {
	this := UserSessionCollection{}
	return &this
}

// GetData returns the Data field value
func (o *UserSessionCollection) GetData() UserSessionsData {
	if o == nil {
		var ret UserSessionsData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *UserSessionCollection) GetDataOk() (*UserSessionsData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *UserSessionCollection) SetData(v UserSessionsData) {
	o.Data = v
}

func (o UserSessionCollection) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserSessionCollection) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *UserSessionCollection) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUserSessionCollection := _UserSessionCollection{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUserSessionCollection)

	if err != nil {
		return err
	}

	*o = UserSessionCollection(varUserSessionCollection)

	return err
}

type NullableUserSessionCollection struct {
	value *UserSessionCollection
	isSet bool
}

func (v NullableUserSessionCollection) Get() *UserSessionCollection {
	return v.value
}

func (v *NullableUserSessionCollection) Set(val *UserSessionCollection) {
	v.value = val
	v.isSet = true
}

func (v NullableUserSessionCollection) IsSet() bool {
	return v.isSet
}

func (v *NullableUserSessionCollection) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserSessionCollection(val *UserSessionCollection) *NullableUserSessionCollection {
	return &NullableUserSessionCollection{value: val, isSet: true}
}

func (v NullableUserSessionCollection) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserSessionCollection) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


