/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ReNewsChainsAuthV1OwnGet400ResponseErrorsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ReNewsChainsAuthV1OwnGet400ResponseErrorsInner{}

// ReNewsChainsAuthV1OwnGet400ResponseErrorsInner struct for ReNewsChainsAuthV1OwnGet400ResponseErrorsInner
type ReNewsChainsAuthV1OwnGet400ResponseErrorsInner struct {
	// Status is the HTTP status code applicable to this problem
	Status int32 `json:"status"`
	// Title is a short, human-readable summary of the problem
	Title string `json:"title"`
	// Code is an application-specific error code, expressed as a string
	Code string `json:"code"`
	// Detail is a human-readable explanation specific to this occurrence of the problem
	Detail *string `json:"detail,omitempty"`
	Meta *ReNewsChainsAuthV1OwnGet400ResponseErrorsInnerMeta `json:"meta,omitempty"`
}

type _ReNewsChainsAuthV1OwnGet400ResponseErrorsInner ReNewsChainsAuthV1OwnGet400ResponseErrorsInner

// NewReNewsChainsAuthV1OwnGet400ResponseErrorsInner instantiates a new ReNewsChainsAuthV1OwnGet400ResponseErrorsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReNewsChainsAuthV1OwnGet400ResponseErrorsInner(status int32, title string, code string) *ReNewsChainsAuthV1OwnGet400ResponseErrorsInner {
	this := ReNewsChainsAuthV1OwnGet400ResponseErrorsInner{}
	this.Status = status
	this.Title = title
	this.Code = code
	return &this
}

// NewReNewsChainsAuthV1OwnGet400ResponseErrorsInnerWithDefaults instantiates a new ReNewsChainsAuthV1OwnGet400ResponseErrorsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReNewsChainsAuthV1OwnGet400ResponseErrorsInnerWithDefaults() *ReNewsChainsAuthV1OwnGet400ResponseErrorsInner {
	this := ReNewsChainsAuthV1OwnGet400ResponseErrorsInner{}
	return &this
}

// GetStatus returns the Status field value
func (o *ReNewsChainsAuthV1OwnGet400ResponseErrorsInner) GetStatus() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *ReNewsChainsAuthV1OwnGet400ResponseErrorsInner) GetStatusOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *ReNewsChainsAuthV1OwnGet400ResponseErrorsInner) SetStatus(v int32) {
	o.Status = v
}

// GetTitle returns the Title field value
func (o *ReNewsChainsAuthV1OwnGet400ResponseErrorsInner) GetTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
func (o *ReNewsChainsAuthV1OwnGet400ResponseErrorsInner) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *ReNewsChainsAuthV1OwnGet400ResponseErrorsInner) SetTitle(v string) {
	o.Title = v
}

// GetCode returns the Code field value
func (o *ReNewsChainsAuthV1OwnGet400ResponseErrorsInner) GetCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *ReNewsChainsAuthV1OwnGet400ResponseErrorsInner) GetCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *ReNewsChainsAuthV1OwnGet400ResponseErrorsInner) SetCode(v string) {
	o.Code = v
}

// GetDetail returns the Detail field value if set, zero value otherwise.
func (o *ReNewsChainsAuthV1OwnGet400ResponseErrorsInner) GetDetail() string {
	if o == nil || IsNil(o.Detail) {
		var ret string
		return ret
	}
	return *o.Detail
}

// GetDetailOk returns a tuple with the Detail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReNewsChainsAuthV1OwnGet400ResponseErrorsInner) GetDetailOk() (*string, bool) {
	if o == nil || IsNil(o.Detail) {
		return nil, false
	}
	return o.Detail, true
}

// HasDetail returns a boolean if a field has been set.
func (o *ReNewsChainsAuthV1OwnGet400ResponseErrorsInner) HasDetail() bool {
	if o != nil && !IsNil(o.Detail) {
		return true
	}

	return false
}

// SetDetail gets a reference to the given string and assigns it to the Detail field.
func (o *ReNewsChainsAuthV1OwnGet400ResponseErrorsInner) SetDetail(v string) {
	o.Detail = &v
}

// GetMeta returns the Meta field value if set, zero value otherwise.
func (o *ReNewsChainsAuthV1OwnGet400ResponseErrorsInner) GetMeta() ReNewsChainsAuthV1OwnGet400ResponseErrorsInnerMeta {
	if o == nil || IsNil(o.Meta) {
		var ret ReNewsChainsAuthV1OwnGet400ResponseErrorsInnerMeta
		return ret
	}
	return *o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReNewsChainsAuthV1OwnGet400ResponseErrorsInner) GetMetaOk() (*ReNewsChainsAuthV1OwnGet400ResponseErrorsInnerMeta, bool) {
	if o == nil || IsNil(o.Meta) {
		return nil, false
	}
	return o.Meta, true
}

// HasMeta returns a boolean if a field has been set.
func (o *ReNewsChainsAuthV1OwnGet400ResponseErrorsInner) HasMeta() bool {
	if o != nil && !IsNil(o.Meta) {
		return true
	}

	return false
}

// SetMeta gets a reference to the given ReNewsChainsAuthV1OwnGet400ResponseErrorsInnerMeta and assigns it to the Meta field.
func (o *ReNewsChainsAuthV1OwnGet400ResponseErrorsInner) SetMeta(v ReNewsChainsAuthV1OwnGet400ResponseErrorsInnerMeta) {
	o.Meta = &v
}

func (o ReNewsChainsAuthV1OwnGet400ResponseErrorsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ReNewsChainsAuthV1OwnGet400ResponseErrorsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	toSerialize["title"] = o.Title
	toSerialize["code"] = o.Code
	if !IsNil(o.Detail) {
		toSerialize["detail"] = o.Detail
	}
	if !IsNil(o.Meta) {
		toSerialize["meta"] = o.Meta
	}
	return toSerialize, nil
}

func (o *ReNewsChainsAuthV1OwnGet400ResponseErrorsInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
		"title",
		"code",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varReNewsChainsAuthV1OwnGet400ResponseErrorsInner := _ReNewsChainsAuthV1OwnGet400ResponseErrorsInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varReNewsChainsAuthV1OwnGet400ResponseErrorsInner)

	if err != nil {
		return err
	}

	*o = ReNewsChainsAuthV1OwnGet400ResponseErrorsInner(varReNewsChainsAuthV1OwnGet400ResponseErrorsInner)

	return err
}

type NullableReNewsChainsAuthV1OwnGet400ResponseErrorsInner struct {
	value *ReNewsChainsAuthV1OwnGet400ResponseErrorsInner
	isSet bool
}

func (v NullableReNewsChainsAuthV1OwnGet400ResponseErrorsInner) Get() *ReNewsChainsAuthV1OwnGet400ResponseErrorsInner {
	return v.value
}

func (v *NullableReNewsChainsAuthV1OwnGet400ResponseErrorsInner) Set(val *ReNewsChainsAuthV1OwnGet400ResponseErrorsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableReNewsChainsAuthV1OwnGet400ResponseErrorsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableReNewsChainsAuthV1OwnGet400ResponseErrorsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReNewsChainsAuthV1OwnGet400ResponseErrorsInner(val *ReNewsChainsAuthV1OwnGet400ResponseErrorsInner) *NullableReNewsChainsAuthV1OwnGet400ResponseErrorsInner {
	return &NullableReNewsChainsAuthV1OwnGet400ResponseErrorsInner{value: val, isSet: true}
}

func (v NullableReNewsChainsAuthV1OwnGet400ResponseErrorsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReNewsChainsAuthV1OwnGet400ResponseErrorsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


