/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SessionsCollection type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SessionsCollection{}

// SessionsCollection struct for SessionsCollection
type SessionsCollection struct {
	Data SessionsCollectionData `json:"data"`
}

type _SessionsCollection SessionsCollection

// NewSessionsCollection instantiates a new SessionsCollection object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSessionsCollection(data SessionsCollectionData) *SessionsCollection {
	this := SessionsCollection{}
	this.Data = data
	return &this
}

// NewSessionsCollectionWithDefaults instantiates a new SessionsCollection object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSessionsCollectionWithDefaults() *SessionsCollection {
	this := SessionsCollection{}
	return &this
}

// GetData returns the Data field value
func (o *SessionsCollection) GetData() SessionsCollectionData {
	if o == nil {
		var ret SessionsCollectionData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *SessionsCollection) GetDataOk() (*SessionsCollectionData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *SessionsCollection) SetData(v SessionsCollectionData) {
	o.Data = v
}

func (o SessionsCollection) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SessionsCollection) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *SessionsCollection) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSessionsCollection := _SessionsCollection{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSessionsCollection)

	if err != nil {
		return err
	}

	*o = SessionsCollection(varSessionsCollection)

	return err
}

type NullableSessionsCollection struct {
	value *SessionsCollection
	isSet bool
}

func (v NullableSessionsCollection) Get() *SessionsCollection {
	return v.value
}

func (v *NullableSessionsCollection) Set(val *SessionsCollection) {
	v.value = val
	v.isSet = true
}

func (v NullableSessionsCollection) IsSet() bool {
	return v.isSet
}

func (v *NullableSessionsCollection) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSessionsCollection(val *SessionsCollection) *NullableSessionsCollection {
	return &NullableSessionsCollection{value: val, isSet: true}
}

func (v NullableSessionsCollection) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSessionsCollection) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


