// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: account.sql

package pgdb

import (
	"context"

	"github.com/google/uuid"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (username, role, status)
VALUES ($1, $2, $3)
RETURNING id, username, role, status, created_at, updated_at, username_updated_at
`

type CreateAccountParams struct {
	Username string
	Role     AccountRole
	Status   AccountStatus
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, createAccount, arg.Username, arg.Role, arg.Status)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UsernameUpdatedAt,
	)
	return i, err
}

const createAccountEmail = `-- name: CreateAccountEmail :one
INSERT INTO account_emails (account_id, email, verified)
VALUES ($1, $2, $3)
RETURNING account_id, email, verified, updated_at, created_at
`

type CreateAccountEmailParams struct {
	AccountID uuid.UUID
	Email     string
	Verified  bool
}

func (q *Queries) CreateAccountEmail(ctx context.Context, arg CreateAccountEmailParams) (AccountEmail, error) {
	row := q.db.QueryRowContext(ctx, createAccountEmail, arg.AccountID, arg.Email, arg.Verified)
	var i AccountEmail
	err := row.Scan(
		&i.AccountID,
		&i.Email,
		&i.Verified,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createAccountPassword = `-- name: CreateAccountPassword :one
INSERT INTO account_passwords (account_id, hash)
VALUES ($1, $2)
RETURNING account_id, hash, updated_at, created_at
`

type CreateAccountPasswordParams struct {
	AccountID uuid.UUID
	Hash      string
}

func (q *Queries) CreateAccountPassword(ctx context.Context, arg CreateAccountPasswordParams) (AccountPassword, error) {
	row := q.db.QueryRowContext(ctx, createAccountPassword, arg.AccountID, arg.Hash)
	var i AccountPassword
	err := row.Scan(
		&i.AccountID,
		&i.Hash,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAccount = `-- name: DeleteAccount :exec
DELETE FROM accounts
WHERE id = $1
`

func (q *Queries) DeleteAccount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteAccount, id)
	return err
}

const getAccountByEmail = `-- name: GetAccountByEmail :one
SELECT a.id, a.username, a.role, a.status, a.created_at, a.updated_at, a.username_updated_at FROM accounts a
JOIN account_emails ae ON a.id = ae.account_id
WHERE ae.email = $1
`

func (q *Queries) GetAccountByEmail(ctx context.Context, email string) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccountByEmail, email)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UsernameUpdatedAt,
	)
	return i, err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, username, role, status, created_at, updated_at, username_updated_at FROM accounts
WHERE id = $1
`

func (q *Queries) GetAccountByID(ctx context.Context, id uuid.UUID) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccountByID, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UsernameUpdatedAt,
	)
	return i, err
}

const getAccountByUsername = `-- name: GetAccountByUsername :one
SELECT id, username, role, status, created_at, updated_at, username_updated_at FROM accounts
WHERE username = $1
`

func (q *Queries) GetAccountByUsername(ctx context.Context, username string) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccountByUsername, username)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UsernameUpdatedAt,
	)
	return i, err
}

const getAccountEmail = `-- name: GetAccountEmail :one
SELECT account_id, email, verified, updated_at, created_at FROM account_emails
WHERE account_id = $1
`

func (q *Queries) GetAccountEmail(ctx context.Context, accountID uuid.UUID) (AccountEmail, error) {
	row := q.db.QueryRowContext(ctx, getAccountEmail, accountID)
	var i AccountEmail
	err := row.Scan(
		&i.AccountID,
		&i.Email,
		&i.Verified,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAccountPassword = `-- name: GetAccountPassword :one
SELECT account_id, hash, updated_at, created_at FROM account_passwords
WHERE account_id = $1
`

func (q *Queries) GetAccountPassword(ctx context.Context, accountID uuid.UUID) (AccountPassword, error) {
	row := q.db.QueryRowContext(ctx, getAccountPassword, accountID)
	var i AccountPassword
	err := row.Scan(
		&i.AccountID,
		&i.Hash,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateAccountPassword = `-- name: UpdateAccountPassword :one
UPDATE account_passwords
SET hash = $2, updated_at = NOW()
WHERE account_id = $1
RETURNING account_id, hash, updated_at, created_at
`

type UpdateAccountPasswordParams struct {
	AccountID uuid.UUID
	Hash      string
}

func (q *Queries) UpdateAccountPassword(ctx context.Context, arg UpdateAccountPasswordParams) (AccountPassword, error) {
	row := q.db.QueryRowContext(ctx, updateAccountPassword, arg.AccountID, arg.Hash)
	var i AccountPassword
	err := row.Scan(
		&i.AccountID,
		&i.Hash,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateAccountStatus = `-- name: UpdateAccountStatus :one
UPDATE accounts
SET status = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, username, role, status, created_at, updated_at, username_updated_at
`

type UpdateAccountStatusParams struct {
	ID     uuid.UUID
	Status AccountStatus
}

func (q *Queries) UpdateAccountStatus(ctx context.Context, arg UpdateAccountStatusParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, updateAccountStatus, arg.ID, arg.Status)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UsernameUpdatedAt,
	)
	return i, err
}

const updateAccountUsername = `-- name: UpdateAccountUsername :one
UPDATE accounts
SET username = $2, updated_at = NOW(), username_set_at = NOW()
WHERE id = $1
RETURNING id, username, role, status, created_at, updated_at, username_updated_at
`

type UpdateAccountUsernameParams struct {
	ID       uuid.UUID
	Username string
}

func (q *Queries) UpdateAccountUsername(ctx context.Context, arg UpdateAccountUsernameParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, updateAccountUsername, arg.ID, arg.Username)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UsernameUpdatedAt,
	)
	return i, err
}

const updateVerifiedEmail = `-- name: UpdateVerifiedEmail :one
UPDATE account_emails
SET verified = $2, updated_at = NOW()
WHERE account_id = $1
RETURNING account_id, email, verified, updated_at, created_at
`

type UpdateVerifiedEmailParams struct {
	AccountID uuid.UUID
	Verified  bool
}

func (q *Queries) UpdateVerifiedEmail(ctx context.Context, arg UpdateVerifiedEmailParams) (AccountEmail, error) {
	row := q.db.QueryRowContext(ctx, updateVerifiedEmail, arg.AccountID, arg.Verified)
	var i AccountEmail
	err := row.Scan(
		&i.AccountID,
		&i.Email,
		&i.Verified,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}
