// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package pgdb

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type AccountRole string

const (
	AccountRoleAdmin     AccountRole = "admin"
	AccountRoleModerator AccountRole = "moderator"
	AccountRoleUser      AccountRole = "user"
)

func (e *AccountRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AccountRole(s)
	case string:
		*e = AccountRole(s)
	default:
		return fmt.Errorf("unsupported scan type for AccountRole: %T", src)
	}
	return nil
}

type NullAccountRole struct {
	AccountRole AccountRole
	Valid       bool // Valid is true if AccountRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAccountRole) Scan(value interface{}) error {
	if value == nil {
		ns.AccountRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AccountRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAccountRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AccountRole), nil
}

type AccountStatus string

const (
	AccountStatusActive      AccountStatus = "active"
	AccountStatusSuspended   AccountStatus = "suspended"
	AccountStatusDeactivated AccountStatus = "deactivated"
)

func (e *AccountStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AccountStatus(s)
	case string:
		*e = AccountStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AccountStatus: %T", src)
	}
	return nil
}

type NullAccountStatus struct {
	AccountStatus AccountStatus
	Valid         bool // Valid is true if AccountStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAccountStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AccountStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AccountStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAccountStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AccountStatus), nil
}

type OutboxEventStatus string

const (
	OutboxEventStatusPending OutboxEventStatus = "pending"
	OutboxEventStatusSent    OutboxEventStatus = "sent"
	OutboxEventStatusFailed  OutboxEventStatus = "failed"
)

func (e *OutboxEventStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OutboxEventStatus(s)
	case string:
		*e = OutboxEventStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OutboxEventStatus: %T", src)
	}
	return nil
}

type NullOutboxEventStatus struct {
	OutboxEventStatus OutboxEventStatus
	Valid             bool // Valid is true if OutboxEventStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOutboxEventStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OutboxEventStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OutboxEventStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOutboxEventStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OutboxEventStatus), nil
}

type Account struct {
	ID                uuid.UUID
	Username          string
	Role              AccountRole
	Status            AccountStatus
	CreatedAt         time.Time
	UpdatedAt         time.Time
	UsernameUpdatedAt time.Time
}

type AccountEmail struct {
	AccountID uuid.UUID
	Email     string
	Verified  bool
	UpdatedAt time.Time
	CreatedAt time.Time
}

type AccountPassword struct {
	AccountID uuid.UUID
	Hash      string
	UpdatedAt time.Time
	CreatedAt time.Time
}

type OutboxEvent struct {
	ID           uuid.UUID
	Topic        string
	EventType    string
	EventVersion int32
	Key          string
	Payload      json.RawMessage
	Status       OutboxEventStatus
	Attempts     int32
	NextRetryAt  time.Time
	CreatedAt    time.Time
	SentAt       sql.NullTime
}

type Session struct {
	ID        uuid.UUID
	AccountID uuid.UUID
	HashToken string
	LastUsed  time.Time
	CreatedAt time.Time
}
