// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: outbox_events.sql

package pgdb

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createOutboxEvent = `-- name: CreateOutboxEvent :one
INSERT INTO outbox_events (
    id, topic, event_type, event_version, key, payload
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, topic, event_type, event_version, key, payload, status, attempts, next_retry_at, created_at, sent_at
`

type CreateOutboxEventParams struct {
	ID           uuid.UUID
	Topic        string
	EventType    string
	EventVersion int32
	Key          string
	Payload      json.RawMessage
}

func (q *Queries) CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) (OutboxEvent, error) {
	row := q.db.QueryRowContext(ctx, createOutboxEvent,
		arg.ID,
		arg.Topic,
		arg.EventType,
		arg.EventVersion,
		arg.Key,
		arg.Payload,
	)
	var i OutboxEvent
	err := row.Scan(
		&i.ID,
		&i.Topic,
		&i.EventType,
		&i.EventVersion,
		&i.Key,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.NextRetryAt,
		&i.CreatedAt,
		&i.SentAt,
	)
	return i, err
}

const getPendingOutboxEvents = `-- name: GetPendingOutboxEvents :many
SELECT id, topic, event_type, event_version, key, payload, status, attempts, next_retry_at, created_at, sent_at FROM outbox_events
WHERE status = 'pending' AND next_retry_at <= (now() AT TIME ZONE 'UTC')
ORDER BY created_at ASC
LIMIT $1
FOR UPDATE SKIP LOCKED
`

func (q *Queries) GetPendingOutboxEvents(ctx context.Context, limit int32) ([]OutboxEvent, error) {
	rows, err := q.db.QueryContext(ctx, getPendingOutboxEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OutboxEvent
	for rows.Next() {
		var i OutboxEvent
		if err := rows.Scan(
			&i.ID,
			&i.Topic,
			&i.EventType,
			&i.EventVersion,
			&i.Key,
			&i.Payload,
			&i.Status,
			&i.Attempts,
			&i.NextRetryAt,
			&i.CreatedAt,
			&i.SentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOutboxEventsSent = `-- name: MarkOutboxEventsSent :exec
UPDATE outbox_events
SET status = 'sent',
    sent_at = $2
WHERE id = ANY($1::uuid[])
`

type MarkOutboxEventsSentParams struct {
	Column1 []uuid.UUID
	SentAt  sql.NullTime
}

func (q *Queries) MarkOutboxEventsSent(ctx context.Context, arg MarkOutboxEventsSentParams) error {
	_, err := q.db.ExecContext(ctx, markOutboxEventsSent, pq.Array(arg.Column1), arg.SentAt)
	return err
}
