openapi: 3.0.0
info:
  title: Cifra SSO REST API
  description: SSO REST API for Cifra services
  version: 0.0.1
paths:
  /test:
    post:
      tags:
        - Test
      description: Test
      responses:
        '201':
          description: successfully
components:
  schemas:
    LoginByEmail:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - type
            - attributes
          properties:
            type:
              type: string
              enum:
                - login
            attributes:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                  description: The account's email address.
                  example: example1312@gmail.com
                password:
                  type: string
                  format: password
                  description: The account's password.
                  example: StrongP@ssw0rd!
    LoginByUsername:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - type
            - attributes
          properties:
            type:
              type: string
              enum:
                - login
            attributes:
              type: object
              required:
                - username
                - password
              properties:
                username:
                  type: string
                  description: The account's username.
                  example: user123
                password:
                  type: string
                  format: password
                  description: The account's password.
                  example: StrongP@ssw0rd!
    Registration:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - type
            - attributes
          properties:
            type:
              type: string
              enum:
                - register_account
            attributes:
              type: object
              required:
                - email
                - password
                - username
              properties:
                email:
                  type: string
                  format: email
                  description: The account's email address.
                  example: example1312@gmail.com
                password:
                  type: string
                  format: password
                  description: The account's password.
                  example: StrongP@ssw0rd!
                username:
                  type: string
                  description: The account's username.
                  example: example_user
    RegistrationAdmin:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - type
            - attributes
          properties:
            type:
              type: string
              enum:
                - register_admin
            attributes:
              type: object
              required:
                - email
                - password
                - username
                - role
              properties:
                email:
                  type: string
                  format: email
                  description: The account's email address.
                  example: example1312@gmail.com
                password:
                  type: string
                  format: password
                  description: The account's password.
                  example: StrongP@ssw0rd!
                username:
                  type: string
                  description: The account's username.
                  example: admin
                role:
                  type: string
                  description: The role assigned to the registering account.
                  enum:
                    - admin
                    - moderator
                  example: admin
    RefreshSession:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - type
            - attributes
          properties:
            type:
              type: string
              enum:
                - refresh_session
            attributes:
              type: object
              required:
                - refresh_token
              properties:
                refresh_token:
                  type: string
                  description: The refresh token to generate a new access token.
                  example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
    UpdatePassword:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - type
            - attributes
          properties:
            type:
              type: string
              enum:
                - update_password
            attributes:
              type: object
              required:
                - old_password
                - new_password
              properties:
                old_password:
                  type: string
                  format: password
                  description: The account's current password.
                  example: OldP@ssw0rd!
                new_password:
                  type: string
                  format: password
                  description: The account's password.
                  example: StrongP@ssw0rd!
    UpdateUsername:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - type
            - attributes
          properties:
            type:
              type: string
              enum:
                - update_username
            attributes:
              type: object
              required:
                - new_username
                - password
              properties:
                new_username:
                  type: string
                  description: The account's new username.
                  example: new_username123
                password:
                  type: string
                  format: password
                  description: The account's current password.
                  example: CurrentP@ssw0rd!
    TokensPair:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - id
            - type
            - attributes
          properties:
            id:
              type: string
              format: uuid
              description: account id
            type:
              type: string
              enum:
                - tokens_pair
            attributes:
              type: object
              required:
                - access_token
                - refresh_token
              properties:
                access_token:
                  type: string
                  description: Access Token
                refresh_token:
                  type: string
                  description: Refresh Token
    AccessToken:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - type
            - attributes
          properties:
            type:
              type: string
              enum:
                - access_token
            attributes:
              type: object
              required:
                - access_token
              properties:
                refresh_token:
                  type: string
                  description: The access token to generate a new access token.
                  example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
    AccountSession:
      type: object
      required:
        - data
      properties:
        data:
          $ref: '#/components/schemas/AccountSessionData'
    AccountSessionData:
      type: object
      required:
        - id
        - type
        - attributes
      properties:
        id:
          type: string
          format: uuid
          description: session id
        type:
          type: string
          enum:
            - account_session
        attributes:
          $ref: '#/components/schemas/AccountSessionAttributes'
    AccountSessionAttributes:
      type: object
      required:
        - account_id
        - created_at
        - last_used
      properties:
        account_id:
          type: string
          format: uuid
          description: account id
        created_at:
          type: string
          format: date-time
          description: session creation date
        last_used:
          type: string
          format: date-time
          description: last used date
    AccountSessionsCollection:
      type: object
      required:
        - data
        - links
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/AccountSessionData'
        links:
          $ref: '#/components/schemas/PaginationData'
    Account:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - id
            - type
            - attributes
          properties:
            id:
              type: string
              format: uuid
              description: account ID
            type:
              type: string
              enum:
                - account
            attributes:
              type: object
              required:
                - username
                - role
                - status
                - created_at
                - updated_at
              properties:
                username:
                  type: string
                  description: The username of the account
                role:
                  type: string
                  description: The role assigned to the account
                status:
                  type: string
                  description: The current status of the account
                created_at:
                  type: string
                  format: date-time
                  description: The date and time when the account was created
                updated_at:
                  type: string
                  format: date-time
                  description: The date and time when the account was last updated
    AccountEmail:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - id
            - type
            - attributes
          properties:
            id:
              type: string
              format: uuid
              description: account ID
            type:
              type: string
              enum:
                - account_email
            attributes:
              type: object
              required:
                - email
                - verified
                - updated_at
              properties:
                email:
                  type: string
                  format: email
                  description: The email address associated with the account
                verified:
                  type: boolean
                  description: Indicates whether the email address has been verified
                updated_at:
                  type: string
                  format: date-time
                  description: The date and time when the email information was last updated
    Errors:
      description: 'Standard JSON:API error'
      type: object
      required:
        - errors
      properties:
        errors:
          type: array
          description: Non empty array of errors occurred during request processing
          items:
            type: object
            required:
              - title
              - status
            properties:
              title:
                type: string
                description: 'Title is a short, human-readable summary of the problem'
                example: Bad Request
              detail:
                type: string
                description: Detail is a human-readable explanation specific to this occurrence of the problem
                example: Request body was expected
              status:
                type: integer
                description: Status is the HTTP status code applicable to this problem
                example: 400
                enum:
                  - 400
                  - 401
                  - 403
                  - 404
                  - 409
                  - 500
    PaginationData:
      type: object
      required:
        - page_number
        - page_size
        - total_items
      properties:
        page_number:
          type: integer
          format: int64
          description: The current page number.
          example: 1
        page_size:
          type: integer
          format: int64
          description: The number of items per page.
          example: 10
        total_items:
          type: integer
          format: int64
          description: The total number of items available.
          example: 100
