openapi: 3.0.0
info:
  title: Cifra SSO REST API
  description: SSO REST API for Cifra services
  version: 0.0.1

paths:
  /test:
    post:
      tags:
        - Test
      description: Test
      responses:
        '201':
          description: successfully

components:
  schemas:
    #requests
    LoginByEmail:
      $ref: './spec/components/schemas/LoginByEmail.yaml'
    LoginByUsername:
      $ref: './spec/components/schemas/LoginByUsername.yaml'
    Registration:
      $ref: './spec/components/schemas/Registration.yaml'
    RegistrationAdmin:
      $ref: './spec/components/schemas/RegistrationAdmin.yaml'
    RefreshSession:
      $ref: './spec/components/schemas/RefreshSession.yaml'
    UpdatePassword:
      $ref: './spec/components/schemas/UpdatePassword.yaml'
    UpdateUsername:
      $ref: './spec/components/schemas/UpdateUsername.yaml'

    #responses
    TokensPair:
        $ref: './spec/components/schemas/TokensPair.yaml'
    AccessToken:
      $ref: './spec/components/schemas/AccessToken.yaml'
    AccountSession:
      $ref: './spec/components/schemas/AccountSession.yaml'
    AccountSessionData:
      $ref: './spec/components/schemas/AccountSessionData.yaml'
    AccountSessionAttributes:
      $ref: './spec/components/schemas/AccountSessionAttributes.yaml'
    AccountSessionsCollection:
      $ref: './spec/components/schemas/AccountSessionsCollection.yaml'
    Account:
      $ref: './spec/components/schemas/Account.yaml'
    AccountEmail:
      $ref: './spec/components/schemas/AccountEmail.yaml'
    Errors:
      $ref: './spec/components/schemas/Errors.yaml'
    PaginationData:
      $ref: './spec/components/schemas/PaginationData.yaml'