// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package core

import (
	"time"

	"github.com/google/uuid"
)

type Account struct {
	ID        uuid.UUID
	Email     string
	Role      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Session struct {
	ID        uuid.UUID
	AccountID uuid.UUID
	Token     string
	Client    string
	Ip        string
	CreatedAt time.Time
	LastUsed  time.Time
}
